#!/usr/bin/env python
import glob
import pandas as pd

list_of_files = []
for file_or_dir in glob.glob("/home/ar1/Desktop/problematic_arms2_4k/*", recursive = True):
        if os.path.isfile(file_or_dir) 
                list_of_mp3s_mp4s.append(file_or_dir)
my_data = pd.DataFrame(list_of_mp3s)
my_data.to_csv("outputfile.xlsx", index = False, header= False)