<?xml version="1.0"?>
        <robot xmlns:xacro="http://wiki.ros.org/xacro"  name="arm">
        
        <!-- the inertial matrix of a solid cylinder-->
        <xacro:macro name="solid_cylinder_inertia" params="radius length mass *origin">
        	<inertial>
		        <mass value="${mass}" />
       				 <xacro:insert_block name="origin" />
				         <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        					  iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
					          izz="${0.5 * mass * radius * radius}" />
        	</inertial>
        </xacro:macro>
        
        
        
        <xacro:property name="base_length" value="3.25"/>
        <xacro:property name="base_radius" value="0.060" />
        <xacro:property name="link0_radius" value="0.060" /> 
          
            <!-- Inertia parameters -->
        <xacro:property name="base_mass" value="1.0" />
        <xacro:property name="link0_mass" value="40.7" />
      
        
        <xacro:property name="link1_mass" value="8.4904" /> 
        <xacro:property name="link2_mass" value="7.3149" />
        <xacro:property name="link3_mass" value="7.314899999999998" />
        <xacro:property name="link4_mass" value="7.3149000000000015" />
        <xacro:property name="link5_mass" value="7.3149000000000015" />
        <xacro:property name="link6_mass" value="7.314899999999994" />
    
        <!-- Radius for each links- UR5 parameters  -->
        <xacro:property name="link1_radius" value="0.06" />
        <xacro:property name="link2_radius" value="0.054" />
        <xacro:property name="link3_radius" value="0.06" />
        <xacro:property name="link4_radius" value="0.04" />
        <xacro:property name="link5_radius" value="0.045" />
        <xacro:property name="link6_radius" value="0.045" />  <!--  joint 0	-->

	<!-- used for fixinig robot to Gazebo 'base_link -->
        <link name="world"/>

            <joint name="${prefix}joint0" type="${revolute}">
            <parent link="${prefix}link-1"/>
            <child link="${prefix}link0" />
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="0.0" friction="0.0"/>
            </joint> 

             <!--  joint 1	-->
            <joint name="${prefix}joint1" type="${revolute}">
            <parent link="${prefix}link0"/>
            <child link="${prefix}link1" />
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.0" friction="0.0"/>
            </joint> 

             <!--  joint 2	-->
            <joint name="${prefix}joint2" type="${revolute}">
            <parent link="${prefix}link1"/>
            <child link="${prefix}link2" />
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.0" friction="0.0"/>
            </joint> 

             <!--  joint 3	-->
            <joint name="${prefix}joint3" type="${revolute}">
            <parent link="${prefix}link2"/>
            <child link="${prefix}link3" />
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.0" friction="0.0"/>
            </joint> 

             <!--  joint 4	-->
            <joint name="${prefix}joint4" type="${revolute}">
            <parent link="${prefix}link3"/>
            <child link="${prefix}link4" />
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="0.0" friction="0.0"/>
            </joint> 

             <!--  joint 5	-->
            <joint name="${prefix}joint5" type="${revolute}">
            <parent link="${prefix}link4"/>
            <child link="${prefix}link5" />
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.0" friction="0.0"/>
            </joint> 

             <!-- link 0	-->
        <link name="${prefix}link0">
        	<visual>
		        <origin xyz="0 0 ${link0_length / 2}" rpy="0 0 0" />
			        <geometry>
        <cylinder radius="${link0_radius}" length="${link0_length}"/>
        </geometry>
        </visual>
        <collision>
        <origin xyz="0 0 ${link0_length / 2 }" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link0_radius}" length="${link0_length}"/>
        </geometry>
        </collision>
        <xacro:cylinder_inertial radius="${link0_radius}" length="${link0_length}" mass="${link0_mass}">
        <origin xyz="0.0 0.0 ${link0_length / 2 }" rpy="0 0 0" />
        </xacro:cylinder_inertial>
        </link> 

             <!-- link 1	-->
        <link name="${prefix}link1">
        <visual>
        <origin xyz="0 0 ${link1_length / 2}" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link1_radius}" length="${link1_length}"/>
        </geometry>
        </visual>
        <collision>
        <origin xyz="0 0 ${link1_length / 2 }" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link1_radius}" length="${link1_length}"/>
        </geometry>
        </collision>
        <xacro:cylinder_inertial radius="${link1_radius}" length="${link1_length}" mass="${link1_mass}">
        <origin xyz="0.0 0.0 ${link1_length / 2 }" rpy="0 0 0" />
        </xacro:cylinder_inertial>
        </link> 

             <!-- link 2	-->
        <link name="${prefix}link2">
        <visual>
        <origin xyz="0 0 ${link2_length / 2}" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link2_radius}" length="${link2_length}"/>
        </geometry>
        </visual>
        <collision>
        <origin xyz="0 0 ${link2_length / 2 }" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link2_radius}" length="${link2_length}"/>
        </geometry>
        </collision>
        <xacro:cylinder_inertial radius="${link2_radius}" length="${link2_length}" mass="${link2_mass}">
        <origin xyz="0.0 0.0 ${link2_length / 2 }" rpy="0 0 0" />
        </xacro:cylinder_inertial>
        </link> 

             <!-- link 3	-->
        <link name="${prefix}link3">
        <visual>
        <origin xyz="0 0 ${link3_length / 2}" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link3_radius}" length="${link3_length}"/>
        </geometry>
        </visual>
        <collision>
        <origin xyz="0 0 ${link3_length / 2 }" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link3_radius}" length="${link3_length}"/>
        </geometry>
        </collision>
        <xacro:cylinder_inertial radius="${link3_radius}" length="${link3_length}" mass="${link3_mass}">
        <origin xyz="0.0 0.0 ${link3_length / 2 }" rpy="0 0 0" />
        </xacro:cylinder_inertial>
        </link> 

             <!-- link 4	-->
        <link name="${prefix}link4">
        <visual>
        <origin xyz="0 0 ${link4_length / 2}" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link4_radius}" length="${link4_length}"/>
        </geometry>
        </visual>
        <collision>
        <origin xyz="0 0 ${link4_length / 2 }" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link4_radius}" length="${link4_length}"/>
        </geometry>
        </collision>
        <xacro:cylinder_inertial radius="${link4_radius}" length="${link4_length}" mass="${link4_mass}">
        <origin xyz="0.0 0.0 ${link4_length / 2 }" rpy="0 0 0" />
        </xacro:cylinder_inertial>
        </link> 

             <!-- link 5	-->
        <link name="${prefix}link5">
        <visual>
        <origin xyz="0 0 ${link5_length / 2}" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link5_radius}" length="${link5_length}"/>
        </geometry>
        </visual>
        <collision>
        <origin xyz="0 0 ${link5_length / 2 }" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${link5_radius}" length="${link5_length}"/>
        </geometry>
        </collision>
        <xacro:cylinder_inertial radius="${link5_radius}" length="${link5_length}" mass="${link5_mass}">
        <origin xyz="0.0 0.0 ${link5_length / 2 }" rpy="0 0 0" />
        </xacro:cylinder_inertial>
        </link> 

             
                     <!-- camera joint - fictive joint -->
            <joint name="camera_joint" type="revolute">
          <parent link="${prefix}link6" />
          <child link = "camera_link" />
          <origin xyz="0.0  0.0 ${link6_length}" rpy="0.0 0.0 0" />
          <axis xyz="0 0 1"/>
          <xacro:joint_limit joint_type="revolute" link_length="0.1"/>
          <dynamics damping="0.0" friction="0.0"/>
            </joint>
        
                <!-- Camera -->
          <link name="camera_link">
          <collision>
            <origin rpy="0 0 0" xyz="0 0 0.005"/>
            <geometry>
            <box size="0.01 0.01 0.01"/>
            </geometry>
          </collision>
        <visual>
            <geometry>
            <box size="0.01 0.01 0.01"/>
            </geometry>
        </visual>
          <xacro:cylinder_inertial radius="0.01" length="0.01" mass="0.01">
            <origin xyz="0.0 0.0 0.005" rpy="0 0 0" />
          </xacro:cylinder_inertial>
        </link>
        
                <!-- ee joint -->
        <joint name="${prefix}ee_fixed_joint" type="fixed">
        <parent link="camera_link" />
        <child link = "${prefix}ee_link" />
        <origin xyz="0.0  0.0 0.01" rpy="0.0 0.0 0.0" />
        </joint>
        
                <!-- ee link -->
        <link name="${prefix}ee_link">
        <collision>
        <geometry>
        <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
        </collision>
        </link>
        
        <xacro:arm_transmission prefix="${prefix}" />
        <xacro:arm_gazebo prefix="${prefix}" />
        </xacro:macro>
        <xacro:arm_robot prefix="" />
    </robot>
